### ISSUE TITLE
Your source code is incomplete, missing source file under common , compile error!

### ISSUE THREAD

**Issue by gmg2719** [VFSSOFT/ASN1#1]
Missing MyArray.h , MyString.h and so on.  would you please add these files?

**Comment by vfssoft** [comment]
> would you please add these files?
No problem, I'll share them soon(a few days). Currently, they're in another repository(and it's private).

But note that the project is still in a VERY EARLY STATE, and I'm stilling find algorithms to implement the functions.

But welcome to contribute if you want.

**Comment by vfssoft** [comment]
The common C++ types are shared at https://github.com/VFSSOFT/common.
